# Generated by Django 2.1.3 on 2018-12-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultdata',
            name='race',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adultdata',
            name='relationship',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adultdata',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=10),
        ),
    ]
